name: Generate Datas

on:
  schedule: # execute every 1 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v3.0.0
        id: snake-gif
        with:
          github_user_name: diogoaraujo017
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: generate-snake-game-from-github-contribution-grid
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

